name = "(F.B.P.) Future Battlefield Pack: Legends"
uid = "5t3edt-btz6-9438-h6ui-967gt56faL1"
version = 3.0
copyright = "Copyright © 2021, CDRMV (aka CDR Deadalus)"
description = "'Future Battlefield Pack Legends' is a Unitpack for Supreme Commander Forged Alliance. It adds adds several new Units based on official GPG Concept Artwork as recreations into the Game."
author = "CDRMV (aka CDR Deadalus)"
url = "http://www.moddb.com/mods/fbp-future-battlefield-pack"
icon = "/mods/Future Battlefield Pack Legends/Icon.png" 
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
