name = "(F.B.P.) Future Battlefield Pack: Legends"
uid = "5t3edt-btz6-9438-h6ui-967gt56faL14"
version = 6
copyright = "Copyright © 2024, CDRMV"
description = "'Future Battlefield Pack Legends' is a Unitpack for Supreme Commander Forged Alliance. It adds adds several new Units based on official GPG Concept Artwork as recreations into the Game. This is an Patch, which fixes several Issues in FAF to make the Mod playable. Keep in Mind this is still an WIP Mod and the Units will get an full Quality Rework in the Future with better looking Models and Textures."
author = "CDRMV"
url = "http://www.moddb.com/mods/fbp-future-battlefield-pack"
icon = "/mods/Future Battlefield Pack Legends/Icon.png" 
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
